### PR TITLE
compatibility with new ini property managment

### PR DESCRIPTION
**Pull request by xgaia**
docker-compose use the new ini property managment, describe in PR  askomics/askomics#213

Also use [xgaia/virtuoso](https://github.com/xgaia/docker-virtuoso) instead of  [tenforce/virtuoso](https://github.com/tenforce/docker-virtuoso) (lighter)

### CODE REVIEW

**Comment by xgaia** [comment]
@abretaud can you merge it ? I don't have the right

**Comment by abretaud** [comment]
Ok, but you pay me a croissant ?

**Comment by xgaia** [comment]
In your dream :croissant:  :sleeping:

**Comment by abretaud** [comment]
Pffff
Can you merge? You should avoir les droits now

**Comment by xgaia** [comment]
Yes thanks!

**Pull request merged**
